### PR TITLE
API SilverStripe 4 compatibility. Add upgrade map, update readme, remove parsedown and include with composer

### PR DESCRIPTION
**Pull request by robbieaverill**
This pull request updates the module for SilverStripe 4.

## Requirements

* Create a new branch from master, i.e. `1` for maintaining SS 3.x support

## Changes

* Implement namespacing, add `.upgrade.yml` mapping
* Remove thirdparty/parsedown, include with composer instead
* Add PSR-4 autoloading, 2.x-dev branch alias
* Update readme to include SS4 usage
* Add Scrutinizer configuration (resolves #5)
* Add .gitattributes (resolves #4)

## Other/notes

I didn't rename "code" to "src" because I didn't want to overload Git so it would lose the history of the classes, but it happened anyway. If you want to, `git mv code src` then commit to be compliant with the new SS4 "best practices" for module development :)

### CODE REVIEW

**Comment by axllent** [comment]
Thanks Robbie! I'll take a look at this later, but just a quick comment and question:

Firstly it is indeed based on undefinedoffset/silverstripe-markdown - and says this clearly in the README.md. Did I miss something, or did you?

Secondly SS4 "best practice" - I'd **love** to know where I can get more information about this. I actually started looking into another module upgrade yesterday (to SS4) but found no documentation whatsoever (about modules, extensions etc). In the latest 4.0.0 alpha I saw `framework/src`, but then also saw `cms/code` - so it's quite conflicting / confusing, not to mention the best practices for when to add namespaces, when not to etc etc. Are you able to point me in the right direction here, hopefully something I can refer to?

**Comment by robbieaverill** [comment]
Re: license, you're totally right! I'm sorry, not sure how I missed it. Will remove that from the issue content in a minute.

**Comment by robbieaverill** [comment]
@axllent re: the SS4 upgrade "best practices" etc, it is a living work-in-progress to update all the documentation. There's been a good start, but there'll still be some gaps.

There's [a full changelog for 4.0.0 to date available here](https://docs.silverstripe.org/en/4/changelogs/4.0.0/) - this contains notes about all changes from 3.5 to 4.0 that you'd need to consider, prioritised from most important to least important as you read down.

The documentation's upgrading guide for 4.0 was recently updated (but hasn't been published to docs.ss yet) - [available here](https://github.com/silverstripe/silverstripe-framework/blob/master/docs/en/03_Upgrading/index.md).

There's also a recently updated (same as above) [guide for extending/creating modules here](https://github.com/silverstripe/silverstripe-framework/blob/master/docs/en/02_Developer_Guides/05_Extending/00_Modules.md).

Regarding `code/` vs `src/`, both will work fine with the way the SilverStripe ClassManifest finds classes, as they're still found anywhere within modules, but the _general_ "best practice" for [PSR-4 autoloading support](http://www.php-fig.org/psr/psr-4/) is to use `src`, and SilverStripe are starting to adopt this from 4.0.0 where possible.

From having upgraded a few modules so far, I've noticed that moving from SS 3.5 to SS 4.0 often involves changing tabs to spaces for PSR-2 compliance, and when you couple that with moving `code/` to `src/` Git often treats it as a deletion and creation rather than a rename and reformat. I believe you can circumvent this by doing each of those major changes in separate pull-requests (not just separate commits within the same pull request).

> ...the best practices for when to add namespaces, when not to etc etc

Your code would continue to work without namespacing in SS4. That being said, for someone to use your globally namespaced (read: not namespaced) class, they'd still have to change `new MarkdownEditor` to `new \MarkdownEditor` or `use MarkdownEditor` at the top of the class declaration. For this reason it makes sense to implement namespacing now, since every SS4 module will have it, and some form of change it required to support namespaced classes anyway.

You're probably aware already, but the convention for namespacing is `Vendor\Package\...` where the `...` is up to you to define as you see fit, but it should match the rule you define for PSR-4 autoloading in composer.json, e.g.:

```json
"autoload": {
    "psr-4": {
        "MyVendor\\MyPackage\\": "src/"
    }
}
```

This in a PSR-4 supported autoloader environment you can call `new \MyVendor\MyPackage\Whatever\MyClass()` and it would autoload to a class named `MyClass` with `namespace MyVendor\MyPackage\Whatever;` that's located at `src/Whatever/MyClass.php`.

Hope this helps!

**Comment by axllent** [comment]
That helps heaps, thank you @robbieaverill 

I have merged your PR and made a couple of changes:
* The `README.md` example forgot to add `use Axllent\Gfmarkdown\Forms\MarkdownEditor;` (or alternatively reference it directly in the `getCmsFields()` ie: `$editor = new Axllent\Gfmarkdown\Forms\MarkdownEditor(` ~ not sure which is better practice)
* I renamed `code` to `src` (and subsequently lost the git history despite following a couple of the suggestion [here](http://stackoverflow.com/questions/10828267/can-git-restructure-my-folders-without-losing-history)). Fortunately not too serious.

I have a bit more reading to do I believe, but your links are most helpful!

**Comment by robbieaverill** [comment]
Great!

We tend to encourage all classes to be imported ("use"d) rather than referencing their fully qualified names.

Feel free to ping me if you have any questions.

Thanks!

**Pull request merged**
